# Host: localhost  (Version 8.0.12)
# Date: 2018-12-20 11:07:52
# Generator: MySQL-Front 6.0  (Build 2.20)


#
# Structure for table "node"
#

DROP TABLE IF EXISTS `node`;
CREATE TABLE `node` (
  `witel` varchar(255) NOT NULL DEFAULT '',
  `name` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`name`,`witel`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

#
# Data for table "node"
#

INSERT INTO `node` VALUES ('TASIKMALAYA','BANJAR'),('TASIKMALAYA','BANJARSARI'),('TASIKMALAYA','CIAMIS'),('TASIKMALAYA','CIAWI'),('TASIKMALAYA','CIBALONG'),('TASIKMALAYA','CIBATU'),('TASIKMALAYA','CIKAJANG'),('TASIKMALAYA','CISOMPET'),('TASIKMALAYA','GARUT'),('TASIKMALAYA','KADUNGORA'),('TASIKMALAYA','KARANGNUNGGAL'),('TASIKMALAYA','KAWALI'),('TASIKMALAYA','LIMBANGAN'),('TASIKMALAYA','MALANGBONG'),('TASIKMALAYA','MANONJAYA'),('TASIKMALAYA','MOBIL DEG Cibatu'),('TASIKMALAYA','MOBIL DEG Tasikmalaya 1'),('TASIKMALAYA','MOBIL DEG Tasikmalaya 2'),('TASIKMALAYA','PAMEUNGPEUK'),('TASIKMALAYA','PANGANDARAN'),('TASIKMALAYA','PARIGI'),('TASIKMALAYA','Plasa Ciamis'),('TASIKMALAYA','Plasa Tasikmalaya'),('TASIKMALAYA','RAJAPOLAH'),('TASIKMALAYA','SINGAPARNA'),('TASIKMALAYA','TASIKMALAYA'),('TASIKMALAYA','Telkom Pramuka Garut'),('TASIKMALAYA','WANARAJA');
